### ISSUE TITLE
wen cloning $ git clone git@github.com:am-MongoDB/MongoDB-Mongopop.git

### ISSUE THREAD

**Issue by nharrisanalyst** [am-MongoDB/Mongopop#2]
I get this error

Cloning into 'MongoDB-Mongopop'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by am-MongoDB** [comment]
For the Git clone, you need to register a public key with your account. Otherwise, you can just download the zip file and use that instead.
