### ISSUE TITLE
Network Error: function toString() { [native code] }

### ISSUE THREAD

**Issue by rgchan2004** [am-MongoDB/Mongopop#3]
When I input the name of atlas connection and put in the mockoroo url.

http://www.mockaroo.com/536ecbc0/download?count=1000&key=48da1ee0

I got the above error message.

Hi Andrew, any idea ?

**Comment by am-MongoDB** [comment]
It's not an error I've seen. Could it be a firewall issue?

If you open up the browser console, do you see any more descriptive error details?

Are you seeing an error on the backend as well?

**Comment by rgchan2004** [comment]
i cannot see any error log. But apparently it is due to http access.
I am using EC2 environment, I have set all inbound http, https permissible. Outbound as usual anything go.
I am not able to update to Atlas

Do I have to create a database in Atlas first ?

**Comment by am-MongoDB** [comment]
Have you added your EC2 instance's IP address to your whitelist in Atlas (or configured VPC peering)?

**Comment by rgchan2004** [comment]
I have added in the EC2 instance IP address to the whitelist in Atals. I did not configured VPC peering.

**Comment by am-MongoDB** [comment]
Adding the IP address should be enough (you need that **or** VPC peering.

Have you got as far as hitting one of the buttons (such as add docs)? If not, then it shouldn't yet be trying to access MongoDB.

What's the MongoDB URI that's being displayed? Have you tried connecting to Atlas with the mongo client using the same details?

**Comment by rgchan2004** [comment]
I suspect, I cannot run it with t2.micro environment.

I managed to get it running on my laptop with Windows.
t2.micro environment seems not to allow me to access Atlas.
IP address of the t2.micro has been added to whitelist of Atlas. But it still does not work.

Strange...
