### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joakimkm** [am-MongoDB/Mongopop#4]
I want to use db.js in a school project and wondering if its possible for you to add a license file.
Thank you very much.

**Comment by am-MongoDB** [comment]
Done – good luck with your project!

**Comment by joakimkm** [comment]
Hmmm. Thank you, but I cant find any license. Last commit was 15 Mar 2017.

**Comment by am-MongoDB** [comment]
My mistake – forgot to merge. You should see it noq
